name: Test NPU
on:
  workflow_dispatch:

jobs:
  Job-npu-1:
    runs-on: linux-arm64-npu-1
    steps:
    - name: Show NPU info
      run: |
        npu-smi info
  Job-npu-2:
    runs-on: linux-arm64-npu-2
    steps:
    - name: Show NPU info
      run: |
        npu-smi info
